add section on setting up linters/language servers
willelz/nvim-lua-guide-ja pull request #1
Opened 2020-11-21 02:58 UTC by hituzi-no-sippo

2020-11-24 13:43 UTC, willelz requested changes
PRありがとうございます。確認をお願いします。

2020-11-24 13:43 UTC, willelz commented on README.ja.md
> +                -- Neovimのランチタイムファイルを言語サーバーに認識させます。
```suggestion
                -- Neovimのランタイムファイルを言語サーバーに認識させます。
```

2020-11-24 13:43 UTC, willelz commented on README.ja.md
> +[sumneko/lua-language-server](https://github.com/sumneko/lua-language-server/)の構成方法の詳細は["Setting without VSCode"](https://github.com/sumneko/lua-language-server/wiki/Setting-without-VSCode)を見てください。
```suggestion
[sumneko/lua-language-server](https://github.com/sumneko/lua-language-server/)の設定方法の詳細は["Setting without VSCode"](https://github.com/sumneko/lua-language-server/wiki/Setting-without-VSCode)を見てください。
```

2020-11-24 13:43 UTC, willelz commented on README.ja.md
> +[coc.nvim](https://github.com/neoclide/coc.nvim/)の[rafcamlet/coc-nvim-lua](https://github.com/rafcamlet/coc-nvim-lua/)の補完ソースはNeovim stdlibの補完項目を提供しています。
```suggestion
[coc.nvim](https://github.com/neoclide/coc.nvim/)の補完ソースである[rafcamlet/coc-nvim-lua](https://github.com/rafcamlet/coc-nvim-lua/)はNeovim stdlibの項目を提供しています。
```

2020-11-24 13:48 UTC, hituzi-no-sippo commented
指摘ありがとうございます。今週金曜日まで確認して修正します。

2020-11-26 02:58 UTC, hituzi-no-sippo commented on README.ja.md
> +                -- `jit` と `bit` のようなLuaJITを言語サーバーに認識させます。
"LuaJITモジュールの `jit` や `bit` (ビット演算ライブラリ)を設定します。"
でどうでしょうか?

2020-11-26 03:08 UTC, hituzi-no-sippo commented on README.ja.md
> +次の構成を `~/.luacheckrc` (もしくは `$XDG_CONFIG_HOME/luacheck/.luacheckrc`)に配置すれば、[luacheck](https://github.com/mpeterv/luacheck/)で `vim` globalsを認識できます。
提案どおりに修正しました。 

https://github.com/willelz/nvim-lua-guide-ja/pull/1/commits/02589363024a4331ec1847e9b0d31d02271ad63c#diff-b3fc642ee9795d9cb415501fb1ca7858d4222eb6f32ae8dc26ae29b3f1934336L948-R948

2020-11-26 03:09 UTC, hituzi-no-sippo commented on README.ja.md
> +[sumneko/lua-language-server](https://github.com/sumneko/lua-language-server/)の設定例です。(例はbuilt-in LSP clientを使っていますが、他のLSP clientでも同じ設定である必要があります）
1c99f21 で"LSPクライアント”に統一させました。

2020-11-26 03:17 UTC, hituzi-no-sippo commented on README.ja.md
> +Luaのプロジェクトでリンターや言語サーバーを使用して、診断と自動補完を利用している場合、Neovim固有の設定が必要になる場合があります。人気のあるツールの推奨設定は次のとおりです。
823d025 で追加しました。

2020-11-26 10:27 UTC, willelz commented on README.ja.md
> +                -- `jit` と `bit` のようなLuaJITを言語サーバーに認識させます。
ここのbitはLua 5.4等のバージョンのことです。(参考https://github.com/sumneko/lua-language-server/blob/master/script/library.lua)
具体的に、`LuaJITやLua 5.4などのバージョンを設定します。`でいいかもしれません。

2020-11-26 10:59 UTC, hituzi-no-sippo commented on README.ja.md
> +                -- `jit` と `bit` のようなLuaJITを言語サーバーに認識させます。
> LuaJITやLua 5.4などのバージョンを設定します。

これ使わせていただきます。
参考先のLSPサーバーのコードを見たのですが、bitが5.4等のバージョンと理解できませんでした。後学のためbitがなんの略かよろしければ教えていただけませんか?

2020-11-26 11:06 UTC, hituzi-no-sippo commented
ご指摘いただいた点は全て修正したつもりです。レビューお願いします。

2020-11-26 11:40 UTC, willelz commented on README.ja.md
> +                -- `jit` と `bit` のようなLuaJITを言語サーバーに認識させます。
期待される値が'LuaJIT'か'Lua 5.1'~'Lua 5.4'なバージョンなことから小数のことかと思います（一般的なのかはわかりません）。

2020-11-26 11:41 UTC, willelz approved these changes

2020-11-26 11:53 UTC, willelz commented
確認しました。ありがとうございました。

2020-11-26 14:36 UTC, hituzi-no-sippo commented
`git pull --rebase` と `git push -f` 使ってコミットを1つにまとめました。
マージお願いします。

2020-11-26 14:52 UTC, merged