Typo fix
willelz/nvim-lua-guide-ja pull request #24
Opened 2022-05-25 23:00 UTC by hituzi-no-sippo

a8300ac6521e02f3b9d8e864e4c7cbd578e9d51a まで和訳する予定です。

2022-05-26 04:12 UTC, hituzi-no-sippo commented on README.ja.md
> +有用な情報(文字列)を表示しません。代わりに `Lua function` を表示します。
`(文字列)` が正しい和訳か自信がありません。

原文 `The
usual way to show information about a keymap like `:nmap <Leader>ex1`
will not output useful information (the string itself),`

2022-05-29 13:17 UTC, willelz requested changes

2022-05-29 13:17 UTC, willelz commented on README.ja.md
> +有用な情報(文字列)を表示しません。代わりに `Lua function` を表示します。
関数で定義されたマッピングは`<Lua function>`とだけ表示されてマッピング内容が表示されないよ。といった感じなので関数の内容そのもののことだと思います。
```suggestion
 `Lua function` とだけ表示され有用な情報（関数の内容自体）が表示されません。
```

2022-05-29 20:25 UTC, hituzi-no-sippo commented on README.ja.md
> +有用な情報(文字列)を表示しません。代わりに `Lua function` を表示します。
提案していただいた内容で修正しました。

2022-05-29 20:26 UTC, hituzi-no-sippo commented
レビューありがとうごぎいます。

指摘していただいた点を修正しました。

2022-05-30 04:43 UTC, merged

2022-05-30 04:43 UTC, willelz commented
ありがとうございます